version: '3.9'

services:
  terasible:
    build:
      context: .
    image: "terasible:1.0"
    container_name: "terasible"
    working_dir: /etc/terasible
    tty: true
    network_mode: host
    restart: always
    volumes:
      - "./work/:/etc/terasible"
